#!/bin/sh
set -e
cd "$(git rev-parse --show-toplevel)"
if [ -z "$(git diff --cached --name-only --diff-filter=ACM)" ]; then exit 0; fi
git diff --cached --name-only --diff-filter=ACM -z | xargs -0 pnpm exec secretlint --no-glob --secretlintrc .secretlintrc.json
